openapi: 3.0.0
info:
  description: |
    Welcome to the legoshichat API, the official interface for the legoshichat. Unlock seamless integration and access the unique features of legoshichat through this official API.
  version: "1.0.0"
  title: legoshichat
  contact:
    email: aryanarora.w1@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: ""
paths:
  /create-account:
    post:
      summary: Create a new user account
      description: Create a new user account and a JWT token.
      tags:
        - "auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        "201":
          description: Account created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type:
                    $ref: "#/components/schemas/User"
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        "400":
          description: Bad Request - Invalid input or missing required fields
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"

        "500":
          description: Internal Server Error - Something went wrong on the server
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"

  /login:
    post:
      summary: User Login
      description: |
        Authenticate a user and generate a JWT token.
      tags:
        - "auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phoneNumber:
                  type: string
                password:
                  type: string
              required:
                - phoneNumber
                - password
      responses:
        "200":
          description: Successfully Authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                      type:
                      $ref: "#/components/schemas/User"
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
  /message/sendById:
    post:
      summary: Send Message by Recipient ID
      description: |
        Send a message to a user using recipientId
      tags:
        - "message"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The message to be sent.
                recipientId:
                  type: string
                  description: The recipient's user ID.
              required:
                - content
                - recipientId
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Message Sent Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type:
                    $ref: "#/components/schemas/ChatMessage"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"

  /message/sendByPhoneNumber:
    post:
      summary: Send Message by Phone Number
      description: |
        Send a message to a user using recipient's Phone Number
      tags:
        - "message"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The message to be sent.
                recipientPhoneNumber:
                  type: string
                  description: The recipient's user ID.
              required:
                - content
                - recipientPhoneNumber
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Message Sent Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type:
                    $ref: "#/components/schemas/ChatMessage"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"

  /messages:
    post:
      summary: Get Messages by Recipient ID
      description: |
        Retrieve messages of a specific recipient in pages.
      tags:
        - "message"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipientId:
                  type: string
                  description: The recipient's ID.
              required:
                - recipientId
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Messages Retrieved Successfully
          content:
            application/json:
              schema:
                properties:
                  page:
                    type: number
                  lastPage:
                    type: boolean
                  messages:
                    type: array
                    items:
                      $ref: "#/components/schemas/ChatMessage"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
  /message/{id}:
    get:
      summary: Get Message by ID
      description: |
        Retrieve a message by its ID.
      tags:
        - "message"
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the message to retrieve.
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Message Retrieved Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type:
                    $ref: "#/components/schemas/ChatMessage"
        "404":
          description: Message Not Found
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"

    delete:
      summary: Delete Message by ID
      description: |
        Delete a message by its ID.
      tags:
        - "message"
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the message to delete.
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Message Deleted Successfully
        "404":
          description: Message Not Found
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
    put:
      summary: Update Message by ID
      description: |
        Update a message by its ID.
      tags:
        - "message"
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the message to update.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The updated content of the message.
              required:
                - content
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Message Updated Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type:
                    $ref: "#/components/schemas/ChatMessage"
        "404":
          description: Message Not Found
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"

  /friends:
    get:
      summary: Retrieve Friends of User
      description: |
        Retrieve a list of friends of authorized in pages.
      tags:
        - "friends"
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Friends Retrieved Successfully
          content:
            application/json:
              schema:
                properties:
                  page:
                    type: number
                  lastPage:
                    type: boolean
                  friends:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
        "404":
          description: User Not Found
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    $ref: "#/components/schemas/Error"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
      required:
        - name
        - phoneNumber
        - password

    ChatMessage:
      type: object
      properties:
        id:
          type: string
          description: The ID of the message.
        content:
          type: string
          description: The content of the message.
        from:
          type: string
          description: The sender's ID.
        to:
          type: string
          description: The recipient's ID.
        timestamp:
          type: string
          format: date-time
          description: The timestamp when the message was sent.
    Error:
      type: object
      properties:
        message:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
